apiVersion: helixsaga.nevercase.io/v1
kind: HelixSaga
metadata:
  name: example-helixsaga
spec:
  config_map:
    volume:
      name: test-conf-volume
      configMap:
        items:
          - key: campaign.yml
            path: campaign.yml
          - key: chat.php
            path: chat.php
          - key: friend.php
            path: friend.php
          - key: game.php
            path: game.php
          - key: gs.php
            path: gs.php
          - key: guildwar.yml
            path: guildwar.yml
          - key: heart.php
            path: heart.php
          - key: inc.php
            path: inc.php
          - key: mysql.php
            path: mysql.php
          - key: push.yml
            path: push.yml
          - key: queue.php
            path: queue.php
          - key: rank.php
            path: rank.php
          - key: redis.php
            path: redis.php
          - key: version.php
            path: version.php
        name: test-conf
    volumeMount:
      mountPath: /var/www/app/conf
      name: test-conf-volume
  applications:
    - spec:
        name: "hs-cn1-version"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/version"
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-game"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/game/index"
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-gmt"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/gmt"
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-friend"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/extensions/friend_server.php", "debug"]
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-rank"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/extensions/rank_server.php", "debug"]
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-heart-register"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/heart/start.php", "start", "-f", "register"]
        containerPorts:
          - containerPort: 5120
            protocol: TCP
        servicePorts:
          - port: 5120
            protocol: TCP
            targetPort: 5120
    - spec:
        name: "hs-cn1-heart-gateway"
        replicas: 2
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/heart/start.php", "start", "-f", "gateway"]
        containerPorts:
          - containerPort: 5321
            protocol: TCP
            name: ext
          - containerPort: 5121
            protocol: TCP
            name: inner
        servicePorts:
          - port: 5321
            protocol: TCP
            targetPort: 5321
            name: ext
          - port: 5121
            protocol: TCP
            targetPort: 5121
            name: inner
    - spec:
        name: "hs-cn1-heart-worker"
        replicas: 5
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/heart/start.php", "start", "-f", "worker"]
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80
    - spec:
        name: "hs-cn1-chat-register"
        replicas: 1
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/chat/start.php", "start", "-f", "register"]
        containerPorts:
          - containerPort: 5120
            protocol: TCP
        servicePorts:
          - port: 5120
            protocol: TCP
            targetPort: 5120
    - spec:
        name: "hs-cn1-chat-gateway"
        replicas: 2
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/chat/start.php", "start", "-f", "gateway"]
        containerPorts:
          - containerPort: 5321
            protocol: TCP
            name: ext
          - containerPort: 5121
            protocol: TCP
            name: inner
        servicePorts:
          - port: 5321
            protocol: TCP
            targetPort: 5321
            name: ext
          - port: 5121
            protocol: TCP
            targetPort: 5121
            name: inner
    - spec:
        name: "hs-cn1-chat-worker"
        replicas: 5
        image: harbor.domain.com/helix-saga/helix-saga-all:latest
        imagePullSecrets:
          - name: private-harbor
        volumePath: /mnt/nas1
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: ENV_ROOT_PATH
            value: "/var/www/app/"
        command: ["php"]
        args: ["/var/www/app/long_connection/chat/start.php", "start", "-f", "worker"]
        containerPorts:
          - containerPort: 80
            protocol: TCP
        servicePorts:
          - port: 80
            protocol: TCP
            targetPort: 80