apiVersion: helixsaga.nevercase.io/v1
kind: HelixSaga
metadata:
  name: example-helixsaga
spec:
  config_map:
    volume:
      name: test-conf-volume
      configMap:
        items:
          - key: campaign.yml
            path: campaign.yml
          - key: chat.php
            path: chat.php
          - key: friend.php
            path: friend.php
          - key: game.php
            path: game.php
          - key: gs.php
            path: gs.php
          - key: guildwar.yml
            path: guildwar.yml
          - key: heart.php
            path: heart.php
          - key: inc.php
            path: inc.php
          - key: mysql.php
            path: mysql.php
          - key: push.yml
            path: push.yml
          - key: queue.php
            path: queue.php
          - key: rank.php
            path: rank.php
          - key: redis.php
            path: redis.php
          - key: version.php
            path: version.php
        name: test-conf
    volumeMount:
      mountPath: /var/www/app/conf
      name: test-conf-volume
  nginx_php_fpm:
  - spec:
      name: "hs-cn1-version"
      replicas: 1
      image: 39.99.229.222:37229/helix-saga/helix-saga-all:latest
      imagePullSecrets:
      - name: private-harbor
      env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ENV_ROOT_PATH
          value: "/var/www/app/version"
  - spec:
      name: "hs-cn1-game"
      replicas: 1
      image: 39.99.229.222:37229/helix-saga/helix-saga-all:latest
      imagePullSecrets:
        - name: private-harbor
      env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ENV_ROOT_PATH
          value: "/var/www/app/game/index"
  - spec:
      name: "hs-cn1-gmt"
      replicas: 1
      image: 39.99.229.222:37229/helix-saga/helix-saga-all:latest
      imagePullSecrets:
        - name: private-harbor
      env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ENV_ROOT_PATH
          value: "/var/www/app/gmt"
  php_swoole:
  - spec:
      name: "hs-cn1-friend"
      replicas: 1
      image: 39.99.229.222:37229/helix-saga/helix-saga-all:latest
      imagePullSecrets:
        - name: private-harbor
      env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: ENV_ROOT_PATH
          value: "/var/www/app/"
      command: ["php"]
      args: ["/var/www/app/extensions/friend_server.php", "debug"]