apiVersion: helixsaga.nevercase.io/v1
kind: HelixSaga
metadata:
  name: example-helixsaga
spec:
  config_map:
    volume:
      name: test-conf-volume
      configMap:
        items:
          - key: mysql.php
            path: mysql.php
          - key: redis.php
            path: redis.php
          - key: version.php
            path: version.php
          - key: gs.php
            path: gs.php
        name: test-conf
    volumeMount:
      mountPath: /var/www/app/conf
      name: test-conf-volume
  version_spec:
    name: "test-version"
    replicas: 1
    image: 39.99.229.222:37229/helix-saga/helix-saga-version:1.0
    imagePullSecrets:
    - name: private-harbor
    env:
      - name: GET_HOSTS_FROM
        value: dns
      - name: ENV_ROOT_PATH
        value: "/var/www/app/version"