apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helixsagas.nevercase.io
spec:
  group: nevercase.io
  version: v1
  names:
    kind: HelixSaga
    plural: helixsagas
  scope: Namespaced